name: Release

on:
  push:
    branches:
      - main

env:
  GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

jobs:
  release:
    name: Release
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
      - name: Build, Test, and Lint
        uses: remedyred/check-action@v1.2.9
        with:
          NO_BAIL: true
          AUTO_COMMIT: true

      - name: Release
        run: pnpm semantic-release
